### PR TITLE
Some fragilities of JS transformer fixed

### LINKED ISSUE #25: Fragile JS transformer
AtomicFU js transformer is fragile. It works for `kotlinx.coroutines` but it is not generally applicable to wider range of libraries. Here is a snippet of produced JS code:

```
(function(root, factory) {
  if (typeof define === 'function' && define.amd) 
    define(['exports', 'kotlin'], factory);
  else if (typeof exports === 'object') 
    factory(module.exports, require('kotlin'));
  else {
    if (typeof kotlin === 'undefined') {
      throw new Error("Error loading module 'kotlinx-coroutines-core'. Its dependency 'kotlin' was not found. Please, check whether 'kotlin' is loaded prior to 'kotlinx-coroutines-core'.");
    }
    if (typeof this['kotlinx-atomicfu'] === 'undefined') {
    }
    root['kotlinx-coroutines-core'] = factory(typeof this['kotlinx-coroutines-core'] === 'undefined' ? {} : this['kotlinx-coroutines-core'], kotlin);
  }
}(this, function(_, Kotlin, $module$kotlinx_atomicfu) {
  'use strict';
...
  var atomic;
  var atomic_0;
....
  $$importsForInline$$['kotlinx-atomicfu'] = $module$kotlinx_atomicfu;
```

Things that should be fixed:
1. ` if (typeof this['kotlinx-atomicfu'] === 'undefined') { ... }` should be completely removed (not just it body), while maintaining line-numbers (fill with appropriate number of blank lines or comments)
2. ` function(_, Kotlin, $module$kotlinx_atomicfu) { ... ` header should be corrected, its `$module$kotlinx_atomicfu` parameters shall be removed at the appropriate position (note, that it may receive additional modules _after_ `kotlinx_atomicfu`)
3. `var atomic;` and `var atmoic_0;` shall be removed completely (replaced with a blank like), not just their right-hand side.
3. ` $$importsForInline$$['kotlinx-atomicfu'] = $module$kotlinx_atomicfu;` line shall be replaced with a blank like (if present).

### PR DESCRIPTION
**Pull request by SokolovaMaria**
Fixes #25

### CODE REVIEW

**Comment by SokolovaMaria** [comment]
[Some fragilities of JS transformer fixed by SokolovaMaria · Pull Request #28 · Kotlin/kotlinx.atomicfu](https://trello.com/c/ysGQDIM1/21-some-fragilities-of-js-transformer-fixed-by-sokolovamaria-pull-request-28-kotlin-kotlinxatomicfu)

**Comment by SokolovaMaria** [comment]
[JS](https://trello.com/c/rZP3IZhA/22-js)

**Comment by elizarov** [comment]
I've rebased it and it does not pass tests. Transformed JS file:

```
(function(root, factory) {
  if (typeof define === 'function' && define.amd) 
    define(['exports', 'kotlin', 'kotlin-test'], factory);
  else if (typeof exports === 'object') 
    factory(module.exports, require('kotlin'), require('kotlinx-atomicfu'), require('kotlin-test'));
  else {
```

Error:

```
/Users/jetbrains/Projects/AtomicFU/atomicfu-js/build/classes/kotlin/test/atomicfu-js_testTransformed.js:5
    factory(module.exports, require('kotlin'), require('kotlinx-atomicfu'), require('kotlin-test'));
    ^
TypeError: Cannot read property 'test' of undefined
    at /Users/jetbrains/Projects/AtomicFU/atomicfu-js/build/classes/kotlin/test/atomicfu-js_testTransformed.js:48:49
```

**Comment by elizarov** [comment]
Merged from another branch

**Pull request closed without merging**
